### ISSUE TITLE
Need help! HMR not work

### ISSUE THREAD

**Issue by Prestapro** [retyui/prestashop-1.7-webpack-hot-module-replacement#1]
Hello,
I cannot make stable build.
HMR not showing in console.
I clone repository edit path and port, try other things but without success.
Also I use Mac os and Mamp server
All change on scss does not save even after reload page

Regards,
Alexandr

**Comment by retyui** [comment]
Hello,

There may be a problem in the ports!
Check the proxy target!
https://github.com/retyui/prestashop-1.7-webpack-hot-module-replacement/blob/master/_dev/hot.webpack.js#L25

### And if possible, send a video of the problem)

**Comment by Prestapro** [comment]
Please, check this video:
https://youtu.be/typ5bfBmnUw

I already done all it steps, but maybe done error.
Regards

**Comment by Prestapro** [comment]
If you specify any other free port, the connection is refused.
http://prntscr.com/emkqti

**Comment by retyui** [comment]
@Prestapro , Я ознакомился с видео, заметил одну особенность,  что при изменении файлов стилей  webpack не делает rebuild.(не обычный способ менять sass фалы через devtools )

Также дублируются слешы в путях к файлам  // 
![image](https://cloud.githubusercontent.com/assets/4661784/24139598/ba5cfd9e-0e2d-11e7-9869-4efe6d2d2847.png)

Что выводит в консоль и в панели network все ресурсы проксируються  находит?

**Comment by Prestapro** [comment]
По поводу изменения стилей через devtools, способ не обычный, но быстрый, про него на Summer Google IO 2016 рассказывали.

C compass/gulp работает отлично, c webpack не получается подружить.
Как-то удалось сделать на 1.7  с browserfy, но задержка в 10 секунд при компиляции убивает все удовольствие от такого редактирования.

И вообще без HMR очень большие задежки при компиляции.

Если ставить одинарные слэши, не дает сохранить.
Пример:
http://prntscr.com/emkx8f
http://prntscr.com/emkxc5

И Network
http://prntscr.com/emky2c


Подключился к 91 порту,
Но в терминале не подхватывает изменения, совсем.
Может попробовать другое окружение?
Не mamp, попробовать собрать с 0

С Уважением,
Александр

**Comment by retyui** [comment]
"Summer Google IO 2016 " смотрел , использовал для css , но что бы для less\sass не додумался использовать) ну да ладно , суть не в этом .

Предлагаю сделать skype call , в не рабочее время , и более подробно уделить внимание ваше проблеме.
мой скайп: offantik

**Comment by retyui** [comment]
prestashop bug! **duplicate slash** :
`http://localhost:3000/prestashop17/themes/classic/assets//js/theme.js`
